version: '3.8'

x-common-variables: &common-variables
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER_KEY}
  DB_KEY: ${DB_USER_SECRET}
  DB_PORT: ${DB_PORT}

services:
  mongo:
      image: "mongo"
      container_name: ${PROJECT_NAME}_database
      restart: always
      volumes:
        - ./db/database:/data/db
        - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      ports:
        - ${DB_PORT}:${DB_PORT}
      environment:
        <<: *common-variables
        MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_KEY}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_SECRET}

  api:
      container_name: ${PROJECT_NAME}_api
      build:
        dockerfile: Dockerfile
        context: "./api"
      volumes:
        - /app/node_modules
        - ./api:/app
      environment:
        <<: *common-variables
        API_PORT: ${API_PORT}
        
  client:
      container_name: ${PROJECT_NAME}_client
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      build:
        dockerfile: Dockerfile
        context: ./client
      volumes:
        - /app/node_modules
        - ./client:/app
      environment:
        CHOKIDAR_USEPOLLING: "true"
        REACT_APP_CLIENT_PORT: ${CLIENT_PORT}
        PORT: ${CLIENT_PORT}

  nginx:
      container_name: ${PROJECT_NAME}_nginx
      depends_on:
        - client
        - api
        - mongo
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:
        - ${GLOBAL_PORT}:${NGINX_PORT}
      environment:
        <<: *common-variables
        NGINX_PORT: ${NGINX_PORT}
        API_PORT: ${API_PORT}
        CLIENT_PORT: ${CLIENT_PORT}

  nginx-prod:
      container_name: ${PROJECT_NAME}_nginx-prod
      depends_on:
        - api
        - mongo
      restart: always
      build:
        dockerfile: Dockerfile.prod
        context: ./nginx
        args:
          CHOKIDAR_USEPOLLING: "true"
          REACT_APP_CLIENT_PORT: ${CLIENT_PORT}
          PORT: ${CLIENT_PORT}
      ports:
        - ${GLOBAL_PORT}:${NGINX_PORT}
      environment:
        <<: *common-variables
        NGINX_PORT: ${NGINX_PORT}
        API_PORT: ${API_PORT}
        CLIENT_PORT: ${CLIENT_PORT}
        CHOKIDAR_USEPOLLING: "true"
        REACT_APP_CLIENT_PORT: ${CLIENT_PORT}
        PORT: ${CLIENT_PORT}