FROM node:14 AS builder

WORKDIR /app

COPY package.json /
COPY package-lock.json /
COPY . / 

RUN npm install

CMD ["npm", "run", "build"]

FROM nginx:1.15-alpine

COPY nginx-default.conf.template /etc/nginx/conf.d/default.conf.template
COPY --from=build-stage /app/build/ /usr/share/nginx/html

COPY docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
